### ISSUE TITLE
Add environment variables automatically

### ISSUE THREAD

**Issue by tabic** [konstruktoid/ansible-docker-rootless#4]
The role should add the environment variables to .profile automatically.

Is there any specific reason why you push a README to the remote host instead of just adding the env variables for the docker_user?

**Comment by konstruktoid** [comment]
Hi @tabic, the reasoning is that the docker_user shouldn't be used unless debugging and the environment variables are configured in the `.service` file, the README is just added as  a simple cheat sheet.

**Comment by tabic** [comment]
Forcing the user to use ansible instead of doing "things" manually is good but in some scenarios it would still be better if the proper environment variables exist. For example if rootfull and rootless docker is running at the same time the docker_user tries to connect to the rootfull daemon which obviously does not work. What about a toggle, disabled by default?

**Comment by konstruktoid** [comment]
Disable what by default?
And I'll update the README regarding the docker_user usage.

**Comment by tabic** [comment]
> Disable what by default?

A toggle in ansible, disabled by default, which adds the required environment variables to .profile automatically.

**Comment by konstruktoid** [comment]
I had a look at this today and adding the environment variables to the user .profile caused various issues; e.g. permissions and overwriting any current settings.
I've added the `add_alias` variable which creates a `docker` alias.

**Comment by rbq** [comment]
I found the README thing quite surprising as well. For me it was dumped in `/root` due to my connection settings and I believe if you deploy multiple users from one privileged account, each will actually overwrite the previous README?

But I ended up writing a wrapper role that performs all the config I need anyway:

* add `XDG_RUNTIME_DIR` line to user's `.profile`
* execute this role
* create a Docker context (via shell), named according to a variable
* patch `docker.json` to point to the new context as the default
* patch `docker.json` to use `log-driver` according to a variable
* smoke test
* remove the README

I'll have a look at the recent changes, but will probably stick to using `docker context` instead of an alias. Does that even work in a non-interactive environment?

**Comment by konstruktoid** [comment]
If you're using Ansible for administration then neither the README, alias, shell script nor `docker context` is needed, those settings are only useful if you have to login and manually manage something.
It will overwrite the previous version if multiple `docker_user` are somehow configured.

The README file and the script should be written in the `"{{ ansible_env.HOME }}"` directory, which shouldn't be `/root` unless you actually connect with the root user.

**Comment by rbq** [comment]
Well, I'm setting up a shared machine where other people deploy Compose apps. Initially they'll log in to configure their registry credentials and try out stuff locally, then they'll probably switch to Ansible/Bash/CI to deploy/backup/etc. In this scenario I do believe that there is some value in setting up an environment that doesn't require additional configuration either way.

Yes, the README ends up in the home directory of the Ansible user, but not the Docker user.

**Comment by konstruktoid** [comment]
> Yes, the README ends up in the home directory of the Ansible user, but not the Docker user.

That's the idea, since no one should be logged in as the Docker user and the Docker daemon (and any containers) should be manage by an admin, the Ansible user in this case.

One solution if that the people you share the machine with is also the docker user, running the rootless docker daemon in their own home directories.
